spring:
  application:
    name: Logitech
  datasource:
    url: jdbc:postgresql://localhost:5432/logitech
    username: postgres
    password: 1004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: 1234


server:
  port: 8090